// MongoDB Atlas Direct Data Insert Script
// Este script inserta los datos de restaurantes directamente en MongoDB Atlas

print('🚀 Connecting to MongoDB Atlas...');
print('Database: tattler-db');
print('Collection: restaurants');
print('');

// Switch to database
use('tattler-db');

// Drop existing collection
print('🗑️  Dropping existing collection...');
db.restaurants.drop();

// Insert restaurant data directly
print('📊 Inserting restaurant data...');

const restaurants = [
  {
    "name": "El Rey del Cabrito",
    "description": "Restaurante tradicional especializado en cabrito y comida norteña, con más de 70 años de tradición culinaria en Monterrey.",
    "category": ["Comida Norteña", "Cabrito", "Tradicional", "Parrilla"],
    "cuisine_type": "Mexicana",
    "phone": "+52-81-8345-4248",
    "email": "info@elreydelcabrito.com.mx",
    "website": "https://www.elreydelcabrito.com.mx/",
    "facebook": "ElReyDelCabritoOficial",
    "instagram": "@elreydelcabrito",
    "street": "Av. Constitución 817 Ote.",
    "neighborhood": "Centro",
    "city": "Monterrey",
    "state": "Nuevo León",
    "country": "México",
    "zipcode": "64000",
    "full_address": "Av. Constitución 817 Ote., Centro, 64000 Monterrey, N.L., México",
    "longitude": -100.3095,
    "latitude": 25.6695,
    "price_level": 3,
    "avg_cost_per_person": 450,
    "min_cost": 300,
    "max_cost": 600,
    "rating": 4.6,
    "total_reviews": 1250,
    "accessibility_wheelchair": true,
    "accessibility_parking": true,
    "delivery_available": true,
    "takeout_available": true,
    "reservations_accepted": true,
    "outdoor_seating": false,
    "wifi_available": true,
    "payment_cash": true,
    "payment_card": true,
    "payment_digital": true,
    "monday_open": "08:00",
    "monday_close": "22:00",
    "tuesday_open": "08:00",
    "tuesday_close": "22:00",
    "wednesday_open": "08:00",
    "wednesday_close": "22:00",
    "thursday_open": "08:00",
    "thursday_close": "22:00",
    "friday_open": "08:00",
    "friday_close": "23:00",
    "saturday_open": "08:00",
    "saturday_close": "23:00",
    "sunday_open": "09:00",
    "sunday_close": "21:00"
  },
  {
    "name": "Tacos El Güero",
    "description": "Taquería local famosa por sus tacos de pastor y carne asada, con salsa verde casera que ha conquistado paladares locales.",
    "category": ["Tacos", "Pastor", "Carne Asada", "Casual"],
    "cuisine_type": "Mexicana",
    "phone": "+52-81-1234-5678",
    "email": "contacto@tacoselguero.mx",
    "website": "https://www.tacoselguero.mx/",
    "facebook": "TacosElGueroMty",
    "instagram": "@tacoselguero",
    "street": "Calle Morelos 234",
    "neighborhood": "Barrio Antiguo",
    "city": "Monterrey",
    "state": "Nuevo León",
    "country": "México",
    "zipcode": "64720",
    "full_address": "Calle Morelos 234, Barrio Antiguo, 64720 Monterrey, N.L., México",
    "longitude": -100.3115,
    "latitude": 25.6721,
    "price_level": 1,
    "avg_cost_per_person": 120,
    "min_cost": 80,
    "max_cost": 180,
    "rating": 4.4,
    "total_reviews": 892,
    "accessibility_wheelchair": false,
    "accessibility_parking": false,
    "delivery_available": true,
    "takeout_available": true,
    "reservations_accepted": false,
    "outdoor_seating": true,
    "wifi_available": false,
    "payment_cash": true,
    "payment_card": true,
    "payment_digital": false,
    "monday_open": "07:00",
    "monday_close": "02:00",
    "tuesday_open": "07:00",
    "tuesday_close": "02:00",
    "wednesday_open": "07:00",
    "wednesday_close": "02:00",
    "thursday_open": "07:00",
    "thursday_close": "02:00",
    "friday_open": "07:00",
    "friday_close": "03:00",
    "saturday_open": "07:00",
    "saturday_close": "03:00",
    "sunday_open": "08:00",
    "sunday_close": "01:00"
  },
  {
    "name": "Mariscos La Perla",
    "description": "Restaurante de mariscos frescos con especialidad en ceviches y pescados a la parrilla, ambiente familiar y vista al mar artificial.",
    "category": ["Mariscos", "Ceviches", "Pescados", "Familiar"],
    "cuisine_type": "Mexicana",
    "phone": "+52-81-9876-5432",
    "email": "reservas@mariscoslaperla.com",
    "website": "https://mariscoslaperla.com/",
    "facebook": "MariscosLaPerla",
    "instagram": "@mariscoslaperla",
    "street": "Av. Lincoln 456",
    "neighborhood": "Mitras Centro",
    "city": "Monterrey",
    "state": "Nuevo León",
    "country": "México",
    "zipcode": "64460",
    "full_address": "Av. Lincoln 456, Mitras Centro, 64460 Monterrey, N.L., México",
    "longitude": -100.3456,
    "latitude": 25.7123,
    "price_level": 2,
    "avg_cost_per_person": 280,
    "min_cost": 200,
    "max_cost": 380,
    "rating": 4.2,
    "total_reviews": 567,
    "accessibility_wheelchair": true,
    "accessibility_parking": true,
    "delivery_available": true,
    "takeout_available": true,
    "reservations_accepted": true,
    "outdoor_seating": true,
    "wifi_available": true,
    "payment_cash": true,
    "payment_card": true,
    "payment_digital": true,
    "monday_open": "11:00",
    "monday_close": "22:00",
    "tuesday_open": "11:00",
    "tuesday_close": "22:00",
    "wednesday_open": "11:00",
    "wednesday_close": "22:00",
    "thursday_open": "11:00",
    "thursday_close": "22:00",
    "friday_open": "11:00",
    "friday_close": "23:00",
    "saturday_open": "10:00",
    "saturday_close": "23:00",
    "sunday_open": "10:00",
    "sunday_close": "21:00"
  },
  {
    "name": "Pizzería Bella Napoli",
    "description": "Auténtica pizzería italiana con horno de leña, ingredientes importados y ambiente acogedor para toda la familia.",
    "category": ["Pizza", "Italiana", "Horno de Leña", "Familia"],
    "cuisine_type": "Italiana",
    "phone": "+52-81-5555-7890",
    "email": "info@bellanapoli.mx",
    "website": "https://www.bellanapoli.mx/",
    "facebook": "BellaNapoliMty",
    "instagram": "@bellanapoli_mty",
    "street": "Calle Hidalgo 789",
    "neighborhood": "Centro",
    "city": "Monterrey",
    "state": "Nuevo León",
    "country": "México",
    "zipcode": "64000",
    "full_address": "Calle Hidalgo 789, Centro, 64000 Monterrey, N.L., México",
    "longitude": -100.3098,
    "latitude": 25.6689,
    "price_level": 2,
    "avg_cost_per_person": 320,
    "min_cost": 250,
    "max_cost": 450,
    "rating": 4.5,
    "total_reviews": 734,
    "accessibility_wheelchair": true,
    "accessibility_parking": false,
    "delivery_available": true,
    "takeout_available": true,
    "reservations_accepted": true,
    "outdoor_seating": false,
    "wifi_available": true,
    "payment_cash": true,
    "payment_card": true,
    "payment_digital": true,
    "monday_open": "12:00",
    "monday_close": "23:00",
    "tuesday_open": "12:00",
    "tuesday_close": "23:00",
    "wednesday_open": "12:00",
    "wednesday_close": "23:00",
    "thursday_open": "12:00",
    "thursday_close": "23:00",
    "friday_open": "12:00",
    "friday_close": "24:00",
    "saturday_open": "12:00",
    "saturday_close": "24:00",
    "sunday_open": "13:00",
    "sunday_close": "22:00"
  },
  {
    "name": "Café Aroma",
    "description": "Cafetería boutique especializada en café de especialidad, repostería artesanal y ambiente perfecto para trabajo remoto.",
    "category": ["Café", "Repostería", "Trabajo Remoto", "Boutique"],
    "cuisine_type": "Café",
    "phone": "+52-81-3333-1111",
    "email": "hola@cafearoma.mx",
    "website": "https://cafearoma.mx/",
    "facebook": "CafeAromaMty",
    "instagram": "@cafe_aroma",
    "street": "Av. Padre Mier 321",
    "neighborhood": "Centro",
    "city": "Monterrey",
    "state": "Nuevo León",
    "country": "México",
    "zipcode": "64000",
    "full_address": "Av. Padre Mier 321, Centro, 64000 Monterrey, N.L., México",
    "longitude": -100.3087,
    "latitude": 25.6712,
    "price_level": 2,
    "avg_cost_per_person": 180,
    "min_cost": 100,
    "max_cost": 250,
    "rating": 4.7,
    "total_reviews": 456,
    "accessibility_wheelchair": true,
    "accessibility_parking": false,
    "delivery_available": true,
    "takeout_available": true,
    "reservations_accepted": false,
    "outdoor_seating": true,
    "wifi_available": true,
    "payment_cash": true,
    "payment_card": true,
    "payment_digital": true,
    "monday_open": "06:30",
    "monday_close": "22:00",
    "tuesday_open": "06:30",
    "tuesday_close": "22:00",
    "wednesday_open": "06:30",
    "wednesday_close": "22:00",
    "thursday_open": "06:30",
    "thursday_close": "22:00",
    "friday_open": "06:30",
    "friday_close": "23:00",
    "saturday_open": "07:00",
    "saturday_close": "23:00",
    "sunday_open": "08:00",
    "sunday_close": "20:00"
  }
];

// Insert all restaurants
const result = db.restaurants.insertMany(restaurants);
print(`✅ Inserted ${result.insertedIds.length} restaurants successfully!`);

// Verify the insertion
const count = db.restaurants.countDocuments();
print(`📊 Total documents in collection: ${count}`);

// Show sample data
print('📋 Sample restaurant:');
printjson(db.restaurants.findOne());

print('');
print('🎉 Sprint 1 CSV import completed successfully!');
print('🔍 To verify data: db.restaurants.find().pretty()');
print('📊 To count records: db.restaurants.countDocuments()');